package it.polimi.graziussi_ouafo.main;

public enum MiscConstants
{
	MIN_PLAYERS(2), MAX_PLAYERS(4),

	NUM_OF_PLAYER_THRESHOLD(2),

	SHEPHERDS_PER_PLAYER_UNDER_OR_EQUALS_THRESHOLD(2), SHEPHERDS_PER_PLAYER_OVER_THRESHOLD(1),

	STARTING_DINARS_UNDER_OR_EQUALS_THRESHOLD(30), STARTING_DINARS_OVER_THRESHOLD(20),

	STARTING_TERRAIN_TILE_PRICE(0), TERRAIN_TILE_INCREMENT(1), MAX_TERRAIN_TILE_PRICE(4),

	STARTING_SHEEP_PER_REGION(1),

	WHITE_SHEEP_FINAL_VALUE(1), BLACK_SHEEP_FINAL_VALUE(2),

	SHEPHERD_LONG_JOURNEY_PRICE(1), SHEPHERD_SILENCE_PRICE(2),

	ACTIONS_PER_TURN(3), STARTING_NORMAL_FENCES(20),

	ROWS_FOR_GAME_INFO(3),

	SERVER_PORT(2222);

	int value;

	private MiscConstants(int value)
	{
		this.value = value;
	}

	public int getValue()
	{
		return this.value;
	}
}
